apiVersion: apps/v1
kind: Deployment
metadata:
  name: recherche-service
spec:
  selector:
    matchLabels:
      app: recherche-service
  template:
    metadata:
      labels:
        app: recherche-service
    spec:
      containers:
        - name: recherche-service
          image: nelahio/recherche-service:latest
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq-clusterip
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmqconn
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmqconn
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: recherche-secret
                  key: recherche-connectionstring
            - name: ENCHERE_SERVICE_URL
              value: http://enchere-clusterip
            - name: PORT
              value: "80"
