networks:
  custom:
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    networks:
      custom:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
    networks:
      custom:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      custom:
  enchere-service:
    image: nelahio/enchere-service:latest
    build:
      context: .
      dockerfile: src/EnchereService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:7777
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=encheres
      - AuthentificationServiceUrl=http://authentification-service
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=http://+:80
    ports:
      - 7001:80
      - 7777:7777
    depends_on:
      - postgres
      - rabbitmq
    networks:
      custom:
  recherche-service:
    image: nelahio/recherche-service:latest
    build:
      context: .
      dockerfile: src/RechercheService/Dockerfile
    environment:
      - DB_URI=mongodb://root:mongopw@mongodb:27017/recherche?authSource=admin
      - PORT=80
      - ENCHERE_SERVICE_URL=http://enchere-service
      - RABBITMQ_HOST=rabbitmq
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      custom:
  authentification-service:
    image: nelahio/authentification-service:latest
    build:
      context: .
      dockerfile: src/AuthentificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=http://app.cube.com
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
      - VIRTUAL_HOST=auth.cube.com
    depends_on:
      - postgres
    networks:
      custom:
        ipv4_address: 10.5.0.200
  gateway-service:
    image: nelahio/gateway-service:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=http://app.cube.com
      - VIRTUAL_HOST=api.cube.com
    networks:
      custom:
  offre-service:
    image: nelahio/offre-service:latest
    build:
      context: .
      dockerfile: src/OffreService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__OffreDbConnection=mongodb://root:mongopw@mongodb
      - AuthentificationServiceUrl=http://authentification-service
      - GrpcEnchere=http://enchere-service:7777
    ports:
      - 7003:80
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      custom:
  notification-service:
    image: nelahio/notification-service:latest
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
    ports:
      - 7004:80
    depends_on:
      - rabbitmq
    networks:
      custom:
  web-app:
    image: nelahio/web-app
    build:
      context: .
      dockerfile: frontend/web-app/Dockerfile
    volumes:
      - /var/lib/web/data
    extra_hosts:
      - auth.cube.com:10.5.0.200
    environment:
      - NEXTAUTH_SECRET=something
      - NEXTAUTH_URL=http://app.cube.com
      - NEXTAUTH_URL_INTERNAL=http://web-app:3000
      - API_URL=http://gateway-service/
      - AUTH_URL=http://auth.cube.com
      - NEXT_PUBLIC_NOTIFY=http://gateway-service/notifications
      - VIRTUAL_HOST=app.cube.com
      - VIRTUAL_PORT=3000
    networks:
      custom:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
    networks:
      custom:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
