apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-password: cG9zdGdyZXNwdw==
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  rabbitmqconn: cmFiYml0
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-username: cm9vdA==
  mongodb-password: bW9uZ29wdw==
---
apiVersion: v1
kind: Secret
metadata:
  name: enchere-secret
type: Opaque
data:
  enchere-connectionstring: U2VydmVyPXBvc3RncmVzLWNsdXN0ZXJpcDo1NDMyO1VzZXIgSWQ9cG9zdGdyZXM7UGFzc3dvcmQ9cG9zdGdyZXNwdztEYXRhYmFzZT1lbmNoZXJlcw==
---
apiVersion: v1
kind: Secret
metadata:
  name: recherche-secret
type: Opaque
data:
  recherche-connectionstring: bW9uZ29kYjovL3Jvb3Q6bW9uZ29wd0Btb25nb2RiLWNsdXN0ZXJpcDoyNzAxNy9yZWNoZXJjaGU/YXV0aFNvdXJjZT1hZG1pbg==
---
apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
type: Opaque
data:
  webapp-nextauth: bmV4dEF1dGhAMjAyNA==
  webapp-clientsecret: c2VjcmV0
---
apiVersion: v1
kind: Secret
metadata:
  name: offre-secret
type: Opaque
data:
  offre-connectionstring: bW9uZ29kYjovL3Jvb3Q6bW9uZ29wd0Btb25nb2RiLWNsdXN0ZXJpcA==
