import { EnvProvider } from "@/env/provider";
import { getCurrentUser } from "./actions/authActions";
import "./globals.css";
import Navbar from "./nav/Navbar";
import SignalRProvider from "./providers/SignalRProvider";
import ToasterProvider from "./providers/ToasterProvider";

export const metadata = {
  title: "Cube",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();
  return (
    <html lang="fr">
      <body>
        <ToasterProvider />
        <Navbar />
        <main className="container mx-auto px-5 pt-10">
          <EnvProvider>
            <SignalRProvider user={user}>{children}</SignalRProvider>
          </EnvProvider>
        </main>
      </body>
    </html>
  );
}
