apiVersion: apps/v1
kind: Deployment
metadata:
  name: offre-service
spec:
  selector:
    matchLabels:
      app: offre-service
  template:
    metadata:
      labels:
        app: offre-service
    spec:
      containers:
        - name: offre-service
          image: nelahio/offre-service:latest
          imagePullPolicy: Always
          env:
            - name: RabbitMq__Host
              value: rabbitmq-clusterip
            - name: RabbitMq__Username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmqconn
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmqconn
            - name: ConnectionStrings__OffreDbConnection
              valueFrom:
                secretKeyRef:
                  name: offre-secret
                  key: offre-connectionstring
            - name: AuthentificationServiceUrl
              value: https://auth.auth-cube.com
            - name: GrpcEnchere
              value: http://enchere-clusterip:7777
