apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: nelahio/notification-service:latest
          imagePullPolicy: Always
          env:
            - name: RabbitMq__Host
              value: rabbitmq-clusterip
            - name: RabbitMq__Username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmqconn
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmqconn
