apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentification-service
spec:
  selector:
    matchLabels:
      app: authentification-service
  template:
    metadata:
      labels:
        app: authentification-service
    spec:
      containers:
        - name: authentification-service
          image: nelahio/authentification-service:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Docker
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ClientApp
              value: http://app.cube.com
            - name: ConnectionStrings__DefaultConnection
              value: Server=postgres-clusterip:5432;User Id=postgres;Password=postgrespw;Database=identity
            - name: VIRTUAL_HOST
              value: auth.cube.com
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: authentification-clusterip
spec:
  selector:
    app: authentification-service
  ports:
    - port: 80
      targetPort: 80
