apiVersion: apps/v1
kind: Deployment
metadata:
  name: enchere-service
spec:
  selector:
    matchLabels:
      app: enchere-service
  template:
    metadata:
      labels:
        app: enchere-service
    spec:
      containers:
        - name: enchere-service
          image: nelahio/enchere-service:latest
          env:
            - name: RabbitMq__Host
              value: rabbitmq-clusterip
            - name: RabbitMq__Username
              value: rabbit
            - name: RabbitMq__Password
              value: rabbit
            - name: ConnectionStrings__DefaultConnection
              value: Server=postgres-clusterip:5432;User Id=postgres;Password=postgrespw;Database=encheres
            - name: AuthentificationServiceUrl
              value: https://auth.auth-cube.com
            - name: Kestrel__Endpoints__Grpc__Protocols
              value: Http2
            - name: Kestrel__Endpoints__Grpc__Url
              value: http://+:7777
            - name: Kestrel__Endpoints__WebApi__Protocols
              value: Http1
            - name: Kestrel__Endpoints__WebApi__Url
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: enchere-clusterip
spec:
  type: ClusterIP
  selector:
    app: enchere-service
  ports:
    - port: 80
      targetPort: 80
      name: web
    - port: 7777
      targetPort: 7777
      name: grpc
