apiVersion: apps/v1
kind: Deployment
metadata:
  name: offre-service
spec:
  selector:
    matchLabels:
      app: offre-service
  template:
    metadata:
      labels:
        app: offre-service
    spec:
      containers:
        - name: offre-service
          image: nelahio/offre-service:latest
          env:
            - name: RabbitMq__Host
              value: rabbitmq-clusterip
            - name: RabbitMq__Username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmqconn
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmqconn
            - name: ConnectionStrings__OffreDbConnection
              valueFrom:
                secretKeyRef:
                  name: offre-secret
                  key: offre-connectionstring
            - name: AuthentificationServiceUrl
              value: https://auth.auth-cube.com
            - name: GrpcEnchere
              value: http://enchere-clusterip:7777
---
apiVersion: v1
kind: Service
metadata:
  name: offre-clusterip
spec:
  type: ClusterIP
  selector:
    app: offre-service
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: offre-secret
type: Opaque
data:
  offre-connectionstring: bW9uZ29kYjovL3Jvb3Q6bW9uZ29wd0Btb25nb2RiLWNsdXN0ZXJpcA==
