apiVersion: apps/v1
kind: Deployment
metadata:
  name: recherche-service
spec:
  selector:
    matchLabels:
      app: recherche-service
  template:
    metadata:
      labels:
        app: recherche-service
    spec:
      containers:
        - name: recherche-service
          image: nelahio/recherche-service:latest
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq-clusterip
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmqconn
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmqconn
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: recherche-secret
                  key: recherche-connectionstring
            - name: ENCHERE_SERVICE_URL
              value: http://enchere-clusterip
            - name: PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: recherche-clusterip
spec:
  type: ClusterIP
  selector:
    app: recherche-service
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: recherche-secret
type: Opaque
data:
  recherche-connectionstring: bW9uZ29kYjovL3Jvb3Q6bW9uZ29wd0Btb25nb2RiLWNsdXN0ZXJpcDoyNzAxNy9yZWNoZXJjaGU/YXV0aFNvdXJjZT1hZG1pbg==
