apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: nelahio/web-app:latest
          env:
            - name: NEXTAUTH_SECRET
              value: something
            - name: NEXTAUTH_URL
              value: https://app.cube.com
            - name: API_URL
              value: http://gateway-clusterip/
            - name: AUTH_URL
              value: https://authentification-clusterip/
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-clusterip
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    - port: 3000
      targetPort: 3000
