apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: nelahio/gateway-service:latest
          env:
            - name: ClientApp
              value: https://app.cube.com
            - name: AuthentificationServiceUrl
              value: https://auth.auth-cube.com
