name: deploy-enchere

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "src/EnchereService/**"

env:
  DOCKERHUB_IMAGE_NAME: enchere-service
  DOCKERFILE_PATH: src/EnchereService/Dockerfile
  DEPLOYMENT_NAME: enchere-service
  DEPLOYMENT_FOLDER: enchere

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE_NAME }}:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save cube

      - name: Apply or restart Kubernetes configuration
        run: |
          kubectl apply -f kubernetes/${{ env.DEPLOYMENT_FOLDER }}
          kubectl rollout restart deployment ${{ env.DEPLOYMENT_NAME }}
