name: deploy-authentification

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "src/AuthentificationService/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/AuthentificationService/Dockerfile
          push: true
          tags: nelahio/authentification-service:latest
